/**
 * モックの越望商機データ。Backend 接続前の UI 検証用（セクション 70, STEP 3）。
 *
 * 実データ接続時（STEP 15）にこのモジュールを API 呼び出しへ差し替える。
 * データはすべて架空であり、実在ブランド・価格を示すものではない。
 */

import type { Opportunity } from "./types";

export const mockOpportunities: Opportunity[] = [
  {
    id: "opp-001",
    name: "折りたたみLEDランタン 充電式",
    brand: "OEM",
    category: "キャンプ用品",
    subCategory: "LEDランタン",
    bestDirection: "CN_TO_JP",
    japanPrice: 4980,
    chinaPrice: 1720,
    priceGapRate: 1.9,
    estimatedProfit: 1680,
    marginRate: 0.34,
    seasonality: "Summer",
    risk: "Low",
    score: 92,
    matchType: "OEM_CANDIDATE",
    matchConfidence: 86,
  },
  {
    id: "opp-002",
    name: "ソロキャンプ用軽量アルミクッカーセット",
    brand: "TrailMate",
    category: "キャンプ用品",
    subCategory: "クッカー",
    bestDirection: "CN_TO_JP",
    japanPrice: 6800,
    chinaPrice: 2950,
    priceGapRate: 1.31,
    estimatedProfit: 1980,
    marginRate: 0.29,
    seasonality: "AllYear",
    risk: "Low",
    score: 88,
    matchType: "MODEL_MATCH",
    matchConfidence: 91,
  },
  {
    id: "opp-003",
    name: "ワンタッチ ドームテント 2人用",
    brand: "TrailMate",
    category: "キャンプ用品",
    subCategory: "ワンタッチテント",
    bestDirection: "CN_TO_JP",
    japanPrice: 12800,
    chinaPrice: 6400,
    priceGapRate: 1.0,
    estimatedProfit: 2760,
    marginRate: 0.22,
    seasonality: "Summer",
    risk: "Medium",
    score: 84,
    matchType: "BRAND_MATCH",
    matchConfidence: 78,
  },
  {
    id: "opp-004",
    name: "折りたたみローチェア アウトドア",
    brand: "OEM",
    category: "キャンプ用品",
    subCategory: "ローチェア",
    bestDirection: "CN_TO_JP",
    japanPrice: 5480,
    chinaPrice: 2380,
    priceGapRate: 1.3,
    estimatedProfit: 1420,
    marginRate: 0.26,
    seasonality: "AllYear",
    risk: "Low",
    score: 81,
    matchType: "SIMILAR",
    matchConfidence: 72,
  },
  {
    id: "opp-005",
    name: "日本製 高性能ガスバーナー CB缶対応",
    brand: "SoraHeat",
    category: "キャンプ用品",
    subCategory: "バーナー",
    bestDirection: "JP_TO_CN",
    japanPrice: 7200,
    chinaPrice: 13400,
    priceGapRate: 0.86,
    estimatedProfit: 3900,
    marginRate: 0.29,
    seasonality: "AllYear",
    risk: "High",
    score: 90,
    matchType: "EXACT",
    matchConfidence: 96,
  },
  {
    id: "opp-006",
    name: "チタン製シングルマグ 450ml",
    brand: "SoraHeat",
    category: "キャンプ用品",
    subCategory: "ケトル",
    bestDirection: "JP_TO_CN",
    japanPrice: 3400,
    chinaPrice: 6200,
    priceGapRate: 0.82,
    estimatedProfit: 1650,
    marginRate: 0.27,
    seasonality: "AllYear",
    risk: "Low",
    score: 86,
    matchType: "EXACT",
    matchConfidence: 94,
  },
  {
    id: "opp-007",
    name: "USB充電式 コンパクトランタン ミニ",
    brand: "OEM",
    category: "キャンプ用品",
    subCategory: "USBランタン",
    bestDirection: "CN_TO_JP",
    japanPrice: 2980,
    chinaPrice: 980,
    priceGapRate: 2.04,
    estimatedProfit: 890,
    marginRate: 0.3,
    seasonality: "Summer",
    risk: "Low",
    score: 79,
    matchType: "OEM_CANDIDATE",
    matchConfidence: 68,
  },
  {
    id: "opp-008",
    name: "折りたたみキャンプテーブル アルミ",
    brand: "TrailMate",
    category: "キャンプ用品",
    subCategory: "キャンプテーブル",
    bestDirection: "CN_TO_JP",
    japanPrice: 8900,
    chinaPrice: 4600,
    priceGapRate: 0.93,
    estimatedProfit: 1780,
    marginRate: 0.2,
    seasonality: "AllYear",
    risk: "Medium",
    score: 74,
    matchType: "MODEL_MATCH",
    matchConfidence: 83,
  },
  {
    id: "opp-009",
    name: "ファミリーテント 大型 5人用",
    brand: "OutFieldPro",
    category: "キャンプ用品",
    subCategory: "ファミリーテント",
    bestDirection: "CN_TO_JP",
    japanPrice: 24800,
    chinaPrice: 15200,
    priceGapRate: 0.63,
    estimatedProfit: 2100,
    marginRate: 0.08,
    seasonality: "Summer",
    risk: "High",
    score: 58,
    matchType: "SIMILAR",
    matchConfidence: 61,
  },
  {
    id: "opp-010",
    name: "ホットサンドメーカー 直火式 IH非対応",
    brand: "OEM",
    category: "キャンプ用品",
    subCategory: "ホットサンドメーカー",
    bestDirection: "CN_TO_JP",
    japanPrice: 3980,
    chinaPrice: 1560,
    priceGapRate: 1.55,
    estimatedProfit: 1180,
    marginRate: 0.3,
    seasonality: "Autumn",
    risk: "Low",
    score: 82,
    matchType: "OEM_CANDIDATE",
    matchConfidence: 74,
  },
  {
    id: "opp-011",
    name: "ガスランタン アウトドア用 マントル式",
    brand: "OutFieldPro",
    category: "キャンプ用品",
    subCategory: "ガスランタン",
    bestDirection: "JP_TO_CN",
    japanPrice: 9800,
    chinaPrice: 16800,
    priceGapRate: 0.71,
    estimatedProfit: 3200,
    marginRate: 0.19,
    seasonality: "Autumn",
    risk: "High",
    score: 76,
    matchType: "BRAND_MATCH",
    matchConfidence: 80,
  },
  {
    id: "opp-012",
    name: "軽量ダウンシュラフ 3シーズン用",
    brand: "OutFieldPro",
    category: "キャンプ用品",
    subCategory: "シュラフ",
    bestDirection: "CN_TO_JP",
    japanPrice: 11800,
    chinaPrice: 5900,
    priceGapRate: 1.0,
    estimatedProfit: 2450,
    marginRate: 0.21,
    seasonality: "Autumn",
    risk: "Medium",
    score: 80,
    matchType: "SIMILAR",
    matchConfidence: 70,
  },
];
